// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AppSetup { id: number, max_menu_nesting_depth: number, access_hash: string, editor_email_domain: string | null, created_at: string, updated_at: string, }