// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
export interface AppSetupRequest { access_code: string, admin_name: string, admin_email: string, admin_password: string, }
