// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AvailabilityRule { id: string, valid_from: string | null, valid_to: string | null, start_time: string | null, end_time: string | null, weekdays: Array<number> | null, active: boolean, }