// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicHolidaysMode } from "./PublicHolidaysMode";

export interface AvailabilityRule { id: string, valid_from: string | null, valid_to: string | null, start_time: string | null, end_time: string | null, weekdays: Array<number> | null, public_holidays_country: string | null, public_holidays_mode: PublicHolidaysMode | null, active: boolean, }