// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateMenuSection } from "./CreateMenuSection";

export interface CreateMenu { restaurant_id: string, name: string, description: string | null, is_active: boolean, permanent: boolean, sections: Array<CreateMenuSection>, }