// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreateOrderSession { restaurant_id: string, start_date: string, end_date: string, allow_late: boolean, }