// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateItem } from "./CreateItem";

export interface CreateMenuSectionItem { position: number, price_override_cents: number | null, is_available: boolean, item: CreateItem, }