// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EitherTag } from "./EitherTag";

export interface CreateItem { restaurant_id: string, name: string, description: string | null, base_price_cents: number, image_url: string | null, tags: Array<EitherTag>, }