// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateOrderItem } from "./CreateOrderItem";

export interface CreateOrder { restaurant_id: string, session_id: string | null, items: Array<CreateOrderItem>, }