// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateOfferSlot } from "./CreateOfferSlot";

export interface CreateOffer { restaurant_id: string, menu_id: string | null, title: string, description: string | null, base_price_cents: number, is_active: boolean, slots: Array<CreateOfferSlot>, }