// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateOfferSlotConstraint } from "./CreateOfferSlotConstraint";

export interface CreateOfferSlot { label: string, min_items: number, max_items: number, supplement_cents: number, constraints: Array<CreateOfferSlotConstraint>, }