// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagInput } from "./TagInput";

export interface CreateItemRequest { restaurant_id: string, name: string, description: string | null, base_price_cents: number, image_url: string | null, tags: Array<TagInput>, }