// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateMenuSectionItem } from "./CreateMenuSectionItem";

export interface CreateMenuSection { menu_id: string, parent_id: string | null, name: string, description: string | null, position: number, is_active: boolean, items: Array<CreateMenuSectionItem>, subsections: Array<CreateMenuSection>, }