// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMethod } from "./AuthMethod";
import type { UserRole } from "./UserRole";

export interface CreateUser { name: string, email: string | null, auth_method: AuthMethod, role: UserRole | null, }