// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tag } from "./Tag";

export interface Item { id: string, restaurant_id: string, name: string, description: string | null, base_price_cents: number, image_url: string | null, active: boolean, created_at: string, updated_at: string, created_by: string, updated_by: string, tags: Array<Tag>, }