// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MenuSectionItem } from "./MenuSectionItem";

export interface MenuSection { id: string, menu_id: string, parent_id: string | null, name: string, description: string | null, position: number, is_active: boolean, created_by: string, updated_by: string, items: Array<MenuSectionItem>, subsections: Array<MenuSection>, }