// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Item } from "./Item";

export interface MenuSectionItem { id: string, section_id: string, position: number, price_override_cents: number | null, is_available: boolean, created_by: string, updated_by: string, item: Item, }