// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MenuSection } from "./MenuSection";

export interface Menu { id: string, restaurant_id: string, name: string, description: string | null, is_active: boolean, permanent: boolean, updated_at: string, created_by: string, updated_by: string, sections: Array<MenuSection>, }