// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MenuScanResponse } from "./MenuScanResponse";

export interface MenuScanJobStatus { job_id: string, status: string, result: MenuScanResponse | null, error: string | null, }