// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScannedSection } from "./ScannedSection";

export interface MenuScanResponse { name: string, description: string | null, sections: Array<ScannedSection>, }