// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfferSlotConstraint } from "./OfferSlotConstraint";

export interface OfferSlot { id: string, offer_id: string, label: string, min_items: number, max_items: number, supplement_cents: number, position: number, slot_group: string | null, constraints: Array<OfferSlotConstraint>, }