// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfferSlot } from "./OfferSlot";

export interface Offer { id: string, restaurant_id: string, menu_id: string | null, title: string, description: string | null, fixed_price_cents: number, is_active: boolean, created_at: string, created_by: string, slots: Array<OfferSlot>, }