// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfferItemCount } from "./OfferItemCount";

export interface OfferSlotSummary { label: string, items: Array<OfferItemCount>, }