// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlotConstraintKind } from "./SlotConstraintKind";

export interface OfferSlotConstraint { id: string, slot_id: string, kind: SlotConstraintKind, supplement_cents: number, }