// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface OrderItem { id: string, order_id: string, item_id: string, item_name: string, item_price_cents: number, slot_id: string | null, slot_label: string | null, slot_group: string | null, notes: string | null, }