// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface OrderItem { id: string, order_id: string, item_id: string, slot_id: string | null, notes: string | null, }