// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderItem } from "./OrderItem";

export interface Order { id: string, user_id: string, user_name: string, restaurant_id: string, session_id: string | null, offer_id: string | null, offer_title: string | null, total_price_cents: number, created_at: string, items: Array<OrderItem>, }