// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface OrderSummary { id: string, user_id: string, session_id: string, total_price_cents: number, item_count: bigint, created_at: string, }