// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderSessionStatus = "Open" | "Closed" | "Cancelled" | "Requested" | "Confirmed" | "Finished";