// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRole } from "./UserRole";

export interface RegisterPasswordUserRequest { name: string, email: string, password: string, role: UserRole, }