// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvailabilityRule } from "./AvailabilityRule";

export interface Restaurant { id: string, name: string, image_url: string | null, phone_number: string | null, sms_phone_number: string | null, address: string | null, created_by: string, updated_by: string, created_at: string, updated_at: string, availability_rule: AvailabilityRule | null, }