// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Restaurant { id: string, name: string, image_url: string | null, created_by: string, updated_by: string, created_at: string, updated_at: string, }