// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SendingMethod } from "./SendingMethod";

export interface RestaurantOrderSettings { id: string, restaurant_id: string, default_start_time: string, default_end_time: string, sending_method: SendingMethod, timezone: string, auto_create_session: boolean, menu_reset_time: string | null, auto_close_session: boolean, notify_on_session_close: boolean, default_pickup_time: string | null, created_at: string, updated_at: string, }