// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScannedTag } from "./ScannedTag";

export interface ScannedItem { name: string, description: string | null, base_price_cents: number, tags: Array<ScannedTag>, }