// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScannedItem } from "./ScannedItem";

export interface ScannedSectionItem { position: number, item: ScannedItem, }