// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScannedSectionItem } from "./ScannedSectionItem";

export interface ScannedSection { name: string, description: string | null, position: number, items: Array<ScannedSectionItem>, subsections: Array<ScannedSection>, }