// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfferGroupSummary } from "./OfferGroupSummary";
import type { RegularItemSummary } from "./RegularItemSummary";

export interface SessionOrderSummary { regular_items: Array<RegularItemSummary>, offer_groups: Array<OfferGroupSummary>, }