// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UnitCreateMenu { restaurant_id: string, name: string, description: string | null, is_active: boolean, permanent: boolean, }