// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UnitCreateItem { restaurant_id: string, name: string, description: string | null, base_price_cents: number, image_url: string | null, active: boolean, }