// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitCreateItem } from "./UnitCreateItem";

export interface UnitCreateMenuSectionItem { section_id: string, position: number, price_override_cents: number | null, is_available: boolean, item: UnitCreateItem, }