// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateAppSetup { max_menu_nesting_depth: number | null, access_hash: string | null, }