// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityRef } from "./EntityRef";
import type { TagInput } from "./TagInput";
import type { UnitCreateMenuSection } from "./UnitCreateMenuSection";
import type { UnitCreateMenuSectionItem } from "./UnitCreateMenuSectionItem";
import type { UpdateMenu } from "./UpdateMenu";
import type { UpdateMenuSection } from "./UpdateMenuSection";
import type { UpdateMenuSectionItem } from "./UpdateMenuSectionItem";

export type UpdateMenuAction = { "UpdateMenu": UpdateMenu } | { "UpdateMenuSection": { section_id: string, update: UpdateMenuSection, } } | { "UpdateMenuSectionItem": { item_id: string, update: UpdateMenuSectionItem, item_tags: Array<TagInput> | null, } } | { "AddSection": { parent_id: EntityRef, section: UnitCreateMenuSection, } } | { "AddItem": { section_id: EntityRef, item: UnitCreateMenuSectionItem, item_tags: Array<TagInput>, } } | { "ChangePositionSection": { section_id: EntityRef, position: number, } } | { "ChangePositionItem": { item_id: EntityRef, position: number, } } | { "ChangeSectionForItem": { item_id: EntityRef, section_id: EntityRef, } } | { "ChangeSectionForSubSection": { subsection_id: EntityRef, section_id: EntityRef, } };