// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SendingMethod } from "./SendingMethod";

export interface UpdateRestaurantOrderSettings { id: string, default_start_time: string, default_end_time: string, sending_method: SendingMethod | null, timezone: string | null, auto_create_session: boolean | null, menu_reset_time: string | null, auto_close_session: boolean | null, notify_on_session_close: boolean | null, }