// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateOrderSession { id: string, start_date: string | null, end_date: string | null, pickup_time: string | null, allow_late: boolean | null, }