// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateMenu { id: string, name: string | null, description: string | null, is_active: boolean | null, permanent: boolean | null, position: number | null, }