// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateMenuAction } from "./UpdateMenuAction";

export interface UpdateMenuActionsRequest { menu_id: string, actions: Array<UpdateMenuAction>, }