// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateItem { id: string, name: string | null, description: string | null, base_price_cents: number | null, image_url: string | null, active: boolean | null, }