// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateOfferSlot } from "./UpdateOfferSlot";

export interface UpdateOffer { id: string, menu_id: string | null, title: string | null, description: string | null, base_price_cents: number | null, is_active: boolean | null, slots: Array<UpdateOfferSlot> | null, }