// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateItem } from "./UpdateItem";

export interface UpdateMenuSectionItem { section_id: string | null, position: number | null, price_override_cents: number | null, is_available: boolean | null, item: UpdateItem | null, }