// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateRestaurant { id: string, name: string | null, image_url: string | null, }