// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMethod } from "./AuthMethod";
import type { UserRole } from "./UserRole";

export interface UpdateUser { id: string, name: string | null, email: string | null, auth_method: AuthMethod | null, role: UserRole | null, }