// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SendingMethod } from "./SendingMethod";

export interface UpdateOrderSettingsRequest { id: string, default_start_time: string | null, default_end_time: string | null, sending_method: SendingMethod | null, timezone: string | null, auto_create_session: boolean | null, menu_reset_time: string | null, update_menu_reset_time: boolean, auto_close_session: boolean | null, }