// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateOfferSlotConstraint } from "./UpdateOfferSlotConstraint";

export interface UpdateOfferSlot { label: string | null, min_items: number | null, max_items: number | null, constraints: Array<UpdateOfferSlotConstraint> | null, }