// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateMenuSection { menu_id: string | null, parent_id: string | null, name: string | null, description: string | null, position: number | null, is_active: boolean | null, }