// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ValidateOfferSelectionResponse { valid: boolean, fixed_price_cents: number, }