// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfferSelectionEntry } from "./OfferSelectionEntry";

export interface ValidateOfferSelectionRequest { restaurant_id: string, selections: Array<OfferSelectionEntry>, }